### ISSUE TITLE
chempot_limits does not recognize multi-element compounds

### ISSUE THREAD

**Issue by misaraty** [materialsproject/pymatgen-analysis-defects#77]
@jmmshn 

Hi,

```
fed = FormationEnergyDiagram.with_directories(
    directory_map={
        "bulk": sc_dir / "bulk_sc",
        0: sc_dir / "q=0",
        -1: sc_dir / "q=-1",
        1: sc_dir / "q=1",
    },
    defect=mg_ga,
    pd_entries=ents,
    dielectric=10,
)
fed.chempot_limits
```

If bulk_sc is specified as a multi-element compound (2 is normal, 5 is abnormal), an error will be reported as follows,

```
C20 H12 N2 O4 Pb
1.0
       16.4335994720         0.0000000000         0.0000000000
        0.0000000000         7.2800998688         0.0000000000
       -4.5973771273         0.0000000000        13.4018847289
   Pb    O    N    C    H
    4   16    8   80   48
Direct
...
```

```
  fed = FormationEnergyDiagram.with_directories(
  File "C:\Users\lenovo\anaconda3\lib\site-packages\pymatgen\analysis\defects\thermo.py", line 363, in with_directories
    return cls(
  File "<string>", line 9, in __init__
  File "C:\Users\lenovo\anaconda3\lib\site-packages\pymatgen\analysis\defects\thermo.py", line 230, in __post_init__
    chempot_limits = self.chempot_diagram.domains[
KeyError: 'H12PbC20(NO2)2'
```

Try modifying ~\anaconda3\Lib\site-packages\pymatgen\analysis\defects\thermo.py, L230-232,

```
        chempot_limits = self.chempot_diagram.domains[
            # self.bulk_entry.composition.reduced_formula
	    self.bulk_entry.composition.composition.anonymized_formula
        ]
```

or

```
        chempot_limits = self.chempot_diagram.domains[
            # self.bulk_entry.composition.reduced_formula
            'H12PbC20N2O4'
        ]
```

or

```
        chempot_limits = self.chempot_diagram.domains[
            # self.bulk_entry.composition.reduced_formula
            'HPbCNO'
        ]
```

The above attempts were unsuccessful.

**Comment by jmmshn** [comment]
Hi @misaraty,
Can you check that the bulk entry you are looking at is indeed on the convex hull of the phase diagram?
This line should make sure that indeed the case but something could have gone wrong:
https://github.com/materialsproject/pymatgen-analysis-defects/blob/824da9ae7a0a0af8fbf37445e5456e3ed349e064/pymatgen/analysis/defects/thermo.py#L216

**Comment by jmmshn** [comment]
Also, whatever entries you are using for the chemical potential calculations, you can try running this code snippet to generate the Chemical Potential diagram outside of the `FormsationEnergyDiagram` object to figure out what happened.

https://github.com/materialsproject/pymatgen-analysis-defects/blob/824da9ae7a0a0af8fbf37445e5456e3ed349e064/pymatgen/analysis/defects/thermo.py#L213-L229

So test this out and if something still does not work, you can send drag the files as a zip drive and I can take a look.

**Comment by misaraty** [comment]
@jmmshn 

There is a size limit for uploading attachments and to test more, so I select a new structure for testing. The calculation parameters are not rigorous, only for code functional testing. 

```
MA-Pb-Cl                              
1.0
        5.6799998283         0.0000000000         0.0000000000
        0.0000000000         5.6799998283         0.0000000000
        0.0000000000         0.0000000000         5.6799998283
    C    N    H   Pb   Cl
    1    1    6    1    3
```

add print,

```
        pd_ = PhaseDiagram(self.pd_entries)
        entries = pd_.stable_entries | {self.bulk_entry}
        pd_ = PhaseDiagram(entries)
        self.phase_diagram = ensure_stable_bulk(pd_, self.bulk_entry)
        print('phase_diagram:', self.phase_diagram)

        entries = []
        for entry in self.phase_diagram.stable_entries:
            d_ = dict(
                energy=self.phase_diagram.get_form_energy(entry),
                composition=entry.composition,
                entry_id=entry.entry_id,
                correction=0.0,
            )
            entries.append(ComputedEntry.from_dict(d_))
            entries.append(ComputedEntry.from_dict(d_))

        self.chempot_diagram = ChemicalPotentialDiagram(entries)
        print('chempot_diagram:', self.chempot_diagram)
```

run code:

```
#!/usr/bin/env python
# -*-coding:utf-8 -*-

import os
# import warnings
# warnings.filterwarnings('ignore')
os.chdir(os.path.split(os.path.realpath(__file__))[0])

print('ref: https://github.com/materialsproject/pymatgen-analysis-defects')

from pathlib import Path
TEST_FILES = Path('./test')
from pymatgen.analysis.defects.thermo import FormationEnergyDiagram
from pymatgen.ext.matproj import MPRester
ents = MPRester('XXX').get_entries_in_chemsys(['Pb','H','C','N','Cl'])
fed = FormationEnergyDiagram.with_directories(
    directory_map={'bulk': TEST_FILES / 'bulk'},
    defect=TEST_FILES / 'defect_0',
    pd_entries=ents,
    dielectric=10,
)
# print('chemical potential:')
# print(fed.chempot_limits)
```

output:

```
ref: https://github.com/materialsproject/pymatgen-analysis-defects
Retrieving ThermoDoc documents: 100%|████████████████████████████████████████████████████████| 641/641 [00:00<?, ?it/s]
phase_diagram: H-Pb-C-N-Cl phase diagram
11 stable phases:
H4C, CCl3, N2, Pb, Cl2, PbCl2, H3N, H4NCl, HCl, H2, C
chempot_diagram: ChemicalPotentialDiagram for C-Cl-H-N-Pb with 22 entries
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\test\test.py", line 16, in <module>
    fed = FormationEnergyDiagram.with_directories(
  File "C:\Users\lenovo\anaconda3\lib\site-packages\pymatgen\analysis\defects\thermo.py", line 365, in with_directories
    return cls(
  File "<string>", line 9, in __init__
  File "C:\Users\lenovo\anaconda3\lib\site-packages\pymatgen\analysis\defects\thermo.py", line 232, in __post_init__
    chempot_limits = self.chempot_diagram.domains[
KeyError: 'H6PbCNCl3'
```
The test files and scripts are as follows: [test.zip](https://github.com/materialsproject/pymatgen-analysis-defects/files/10311860/test.zip)

The above code works fine for GaN, both the official example and my recalculated GaN structure.

**Comment by jmmshn** [comment]
@misaraty thanks for reporting this, this was indeed a bug it has been fixed in #81

**Comment by misaraty** [comment]
@jmmshn Received with thanks.

**Comment by jmmshn** [comment]
I would be very careful with combining your calculations with MP calculations for stability analysis.  You can try calculate elemental entries yourself and just use the formation energies from MP to construct the phase diagram.  I'll make a tutorial at some point but it is documented in the code itself.
